// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// blockMatrixConstruction
void blockMatrixConstruction(int method, unsigned n, unsigned m);
RcppExport SEXP _HessianScreening_blockMatrixConstruction(SEXP methodSEXP, SEXP nSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< unsigned >::type n(nSEXP);
    Rcpp::traits::input_parameter< unsigned >::type m(mSEXP);
    blockMatrixConstruction(method, n, m);
    return R_NilValue;
END_RCPP
}
// lassoPath
Rcpp::List lassoPath(SEXP X, arma::vec y, const std::string family, const bool standardize, const std::string screening_type, const bool hessian_warm_starts, const bool approx_hessian, const arma::uword path_length, const arma::uword maxit, const double tol_decr, const double tol_infeas, const double tol_gap, const double gamma, const bool verify_hessian, const arma::uword verbosity);
RcppExport SEXP _HessianScreening_lassoPath(SEXP XSEXP, SEXP ySEXP, SEXP familySEXP, SEXP standardizeSEXP, SEXP screening_typeSEXP, SEXP hessian_warm_startsSEXP, SEXP approx_hessianSEXP, SEXP path_lengthSEXP, SEXP maxitSEXP, SEXP tol_decrSEXP, SEXP tol_infeasSEXP, SEXP tol_gapSEXP, SEXP gammaSEXP, SEXP verify_hessianSEXP, SEXP verbositySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< const bool >::type standardize(standardizeSEXP);
    Rcpp::traits::input_parameter< const std::string >::type screening_type(screening_typeSEXP);
    Rcpp::traits::input_parameter< const bool >::type hessian_warm_starts(hessian_warm_startsSEXP);
    Rcpp::traits::input_parameter< const bool >::type approx_hessian(approx_hessianSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type path_length(path_lengthSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_decr(tol_decrSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_infeas(tol_infeasSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_gap(tol_gapSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const bool >::type verify_hessian(verify_hessianSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type verbosity(verbositySEXP);
    rcpp_result_gen = Rcpp::wrap(lassoPath(X, y, family, standardize, screening_type, hessian_warm_starts, approx_hessian, path_length, maxit, tol_decr, tol_infeas, tol_gap, gamma, verify_hessian, verbosity));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HessianScreening_blockMatrixConstruction", (DL_FUNC) &_HessianScreening_blockMatrixConstruction, 3},
    {"_HessianScreening_lassoPath", (DL_FUNC) &_HessianScreening_lassoPath, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_HessianScreening(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
