# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blockMatrixConstruction <- function(method = 0L, n = 9000L, m = 50L) {
    invisible(.Call(`_HessianScreening_blockMatrixConstruction`, method, n, m))
}

denseInnerProduct <- function(method = 0L, n = 100L, p = 1000L, m = 50L) {
    invisible(.Call(`_HessianScreening_denseInnerProduct`, method, n, p, m))
}

sparseInnerProduct <- function(method = 0L, n = 100L, p = 1000L, m = 50L, density = 0.1, n_threads = 4L) {
    invisible(.Call(`_HessianScreening_sparseInnerProduct`, method, n, p, m, density, n_threads))
}

#' Fit the Lasso Path
#'
#' @param X The predictor matrix
#' @param y The reponse vector
#' @param family The name of the famioy, "gaussian" or "logistic"
#' @param standardize Whether to standardize the predictors
#' @param screening_type Which screening type to use, currently
#'        `"hessian"`, `"working"`,`"gap_safe"`, or `"edpp"`.
#' @param hessian_warm_starts Whether to use warm starts based on Hessian
#' @param approx_hessian Whether to approximate Hessian in the logistic
#'        regression case
#' @param path_length The length of the lasso path
#' @param maxit Maximum number of iterations for Coordinate Descent loop
#' @param tol_decr Tolerance threshold for change in primal value
#' @param tol_infeas Tolerance threshold for maximum infeasibility
#' @param tol_gap Tolerance threshold for duality gap
#' @param gamma Percent of strong approximation to add to Hessian
#'        approximation
#' @param verify_hessian Whether ot not to verify that Hessian
#'        updates are correct. Used only for diagnostic purposes.
#' @param verbosity Controls the level of verbosity. 0 = no output.
#' @export
lassoPath <- function(X, y, family = "gaussian", standardize = TRUE, screening_type = "working", hessian_warm_starts = TRUE, approx_hessian = TRUE, path_length = 100L, maxit = 1e5L, tol_decr = 1e-7, tol_infeas = 1e-5, tol_gap = 1e-4, gamma = 0.01, verify_hessian = FALSE, verbosity = 0L) {
    .Call(`_HessianScreening_lassoPath`, X, y, family, standardize, screening_type, hessian_warm_starts, approx_hessian, path_length, maxit, tol_decr, tol_infeas, tol_gap, gamma, verify_hessian, verbosity)
}

