// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lassoPathDense
Rcpp::List lassoPathDense(arma::mat X, arma::vec y, const std::string family, const bool standardize, const std::string screening_type, const bool hessian_warm_starts, std::string log_hessian_update_type, const arma::uword path_length, const arma::uword maxit, const double tol_infeas, const double tol_gap, const double gamma, const bool verify_hessian, const bool force_kkt_check, const arma::uword verbosity);
RcppExport SEXP _HessianScreening_lassoPathDense(SEXP XSEXP, SEXP ySEXP, SEXP familySEXP, SEXP standardizeSEXP, SEXP screening_typeSEXP, SEXP hessian_warm_startsSEXP, SEXP log_hessian_update_typeSEXP, SEXP path_lengthSEXP, SEXP maxitSEXP, SEXP tol_infeasSEXP, SEXP tol_gapSEXP, SEXP gammaSEXP, SEXP verify_hessianSEXP, SEXP force_kkt_checkSEXP, SEXP verbositySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< const bool >::type standardize(standardizeSEXP);
    Rcpp::traits::input_parameter< const std::string >::type screening_type(screening_typeSEXP);
    Rcpp::traits::input_parameter< const bool >::type hessian_warm_starts(hessian_warm_startsSEXP);
    Rcpp::traits::input_parameter< std::string >::type log_hessian_update_type(log_hessian_update_typeSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type path_length(path_lengthSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_infeas(tol_infeasSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_gap(tol_gapSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const bool >::type verify_hessian(verify_hessianSEXP);
    Rcpp::traits::input_parameter< const bool >::type force_kkt_check(force_kkt_checkSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type verbosity(verbositySEXP);
    rcpp_result_gen = Rcpp::wrap(lassoPathDense(X, y, family, standardize, screening_type, hessian_warm_starts, log_hessian_update_type, path_length, maxit, tol_infeas, tol_gap, gamma, verify_hessian, force_kkt_check, verbosity));
    return rcpp_result_gen;
END_RCPP
}
// lassoPathSparse
Rcpp::List lassoPathSparse(arma::sp_mat X, arma::vec y, const std::string family, const bool standardize, const std::string screening_type, const bool hessian_warm_starts, std::string log_hessian_update_type, const arma::uword path_length, const arma::uword maxit, const double tol_infeas, const double tol_gap, const double gamma, const bool verify_hessian, const bool force_kkt_check, const arma::uword verbosity);
RcppExport SEXP _HessianScreening_lassoPathSparse(SEXP XSEXP, SEXP ySEXP, SEXP familySEXP, SEXP standardizeSEXP, SEXP screening_typeSEXP, SEXP hessian_warm_startsSEXP, SEXP log_hessian_update_typeSEXP, SEXP path_lengthSEXP, SEXP maxitSEXP, SEXP tol_infeasSEXP, SEXP tol_gapSEXP, SEXP gammaSEXP, SEXP verify_hessianSEXP, SEXP force_kkt_checkSEXP, SEXP verbositySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< const std::string >::type family(familySEXP);
    Rcpp::traits::input_parameter< const bool >::type standardize(standardizeSEXP);
    Rcpp::traits::input_parameter< const std::string >::type screening_type(screening_typeSEXP);
    Rcpp::traits::input_parameter< const bool >::type hessian_warm_starts(hessian_warm_startsSEXP);
    Rcpp::traits::input_parameter< std::string >::type log_hessian_update_type(log_hessian_update_typeSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type path_length(path_lengthSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_infeas(tol_infeasSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_gap(tol_gapSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const bool >::type verify_hessian(verify_hessianSEXP);
    Rcpp::traits::input_parameter< const bool >::type force_kkt_check(force_kkt_checkSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type verbosity(verbositySEXP);
    rcpp_result_gen = Rcpp::wrap(lassoPathSparse(X, y, family, standardize, screening_type, hessian_warm_starts, log_hessian_update_type, path_length, maxit, tol_infeas, tol_gap, gamma, verify_hessian, force_kkt_check, verbosity));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HessianScreening_lassoPathDense", (DL_FUNC) &_HessianScreening_lassoPathDense, 15},
    {"_HessianScreening_lassoPathSparse", (DL_FUNC) &_HessianScreening_lassoPathSparse, 15},
    {NULL, NULL, 0}
};

RcppExport void R_init_HessianScreening(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
